//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MehmetBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriHesap
    {
        public int ID { get; set; }
        public Nullable<int> Musteri_ID { get; set; }
        public string KartNumarası { get; set; }
        public string SonKullanmaAy { get; set; }
        public string SonKullanmaYıl { get; set; }
        public string Cvv { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
